### ISSUE TITLE
Incomplete Message Received When Sending Message Larger Than Buffer Size Using NamedPipes

### ISSUE THREAD

**Issue by JKamsker** [dotnet/Nerdbank.Streams#700]
I am currently using NamedPipes from `System.IO.Pipes` in conjunction with `MultiplexingStream` and I've encountered an issue where sending a message that is larger than the buffer size results in an incomplete message being received on the other end. 

I've attempted to create a simple reproducible case, but oddly enough, the issue doesn't seem to manifest in the reproducible environment, only in my actual application. I'm unable to pinpoint the exact cause of this issue and was hoping someone might have some insights or suggestions as to what could be causing this.

Here is the relevant section of my code:

```csharp
// Sender:
var iStream = channel.Input.AsStream();
var oStream = channel.Output.AsStream();

var data = await JsonSerializer.DeserializeAsync<TData>(iStream);
var result = await handler(ctx, data);
await JsonSerializer.SerializeAsync(oStream, result);
await oStream.FlushAsync();
await oStream.DisposeAsync();

await channel.Output.CompleteAsync();

// Receiver:
var iStream = channel.Input.AsStream();

var ms = new MemoryStream();
await input.CopyToAsync(ms);
ms.Position = 0;
var msString = Encoding.UTF8.GetString(ms.ToArray());
return await JsonSerializer.DeserializeAsync<TResponse>(ms);
```

I can provide access to the actual application for anyone who might be able to assist with this issue. Any help or guidance would be greatly appreciated. Thanks in advance!

## Expected behavior

When sending a message, even one that is larger than the buffer size, the entire message should be received intact on the other end.

## Actual behavior

When sending a message that is larger than the buffer size, an incomplete message is received on the other end.

## Possible Solution

Unknown at this time. It seems to work in a reproducible environment, but not in the actual application.

**Comment by JKamsker** [comment]
After some debugging i found out that adding a delay of 50ms in the sender,  before the completion "solves" the issue.
There seems to be a race condition somewhere in the  library.

```csharp
var ms = new MemoryStream();
await JsonSerializer.SerializeAsync(ms, result);
ms.Position = 0;
var msString = Encoding.UTF8.GetString(ms.ToArray());

//await ms.CopyToAsync(oStream);

var fres = await channel.Output.WriteAsync(ms.ToArray());
await channel.Output.FlushAsync();
await Task.Delay(50);
await channel.Output.CompleteAsync();
```

**Comment by JKamsker** [comment]
Update: The channel was disposed after flush&completeAsync which led to the channel being disposed before the pending data was sent.
Looks counter intuitive to me

**Comment by AArnott** [comment]
The issue is that you're explicitly disposing channels. This is counter to the API docs, which mentions the outcome you're seeing specifically:
https://github.com/dotnet/Nerdbank.Streams/blob/17998b25c219d525600fb839eeae2ec3200c15b5/src/Nerdbank.Streams/MultiplexingStream.Channel.cs#L327-L330

**Comment by JKamsker** [comment]
@AArnott Yes, i understand that now. But still, i expected pipewriter.flushasync to wait until the data is flushed to the remote.

If that's not possible, could something be implemented which waits for the current buffered data to be sent?

**Comment by AArnott** [comment]
`PipeWriter.FlushAsync` doesn't behave like `Stream.FlushAsync`. Its documented behavior is merely that it makes the buffer available to the reader. In the case of a MultiplexingStream.Channel, the reader is also in the same process as you, as it's reading what you've written and transmitting it across the multiplexing stream. But when you dispose the channel, you cut off the transport over which transmission happens. 
So I'm afraid offering a `Complete()` method and a `Completion` property for you to await on is the best thing I can offer.
