### ISSUE TITLE
`PipeWriter`-to-`WebSocket` can combine too many messages into one.

### ISSUE THREAD

**Issue by airbreather** [dotnet/Nerdbank.Streams#726]
I'm not sure how much of a showstopper this is, but I've created a failing test in d25f1dc5e2d0e817093d571197e9b3df1deed4b3 that demonstrates it: https://github.com/dotnet/Nerdbank.Streams/blob/d25f1dc5e2d0e817093d571197e9b3df1deed4b3/test/Nerdbank.Streams.Tests/PipeExtensionsTests.cs#L230-L252

This test fails after writing (for me) nothing ever higher than "1" to the console, output looks something like:
```
0
1
[xUnit.net 00:00:00.85]     PipeExtensionsTests.UsePipeWriter_WebSocket_SeparateMessagesForSeparateWrites [FAIL]
  Failed PipeExtensionsTests.UsePipeWriter_WebSocket_SeparateMessagesForSeparateWrites [7 ms]
  Error Message:
   Assert.Equal() Failure: Collections differ
Expected: [···, 5, 6]
Actual:   [···, 5, 6, 4, 5, 6]
                      ↑ (pos 3)
  Stack Trace:
     at PipeExtensionsTests.UsePipeWriter_WebSocket_SeparateMessagesForSeparateWrites() in /the/path/to/Nerdbank.Streams/test/Nerdbank.Streams.Tests/PipeExtensionsTests.cs:line 250
--- End of stack trace from previous location ---
```

I'm going to put any more analysis I have into a separate comment on this thread because I wanted to keep this first comment relatively free of my own (possibly faulty) analysis... as I mentioned elsewhere, I'm still getting to know `System.IO.Pipelines`, so it seems possible that this is actually the expected behavior.

### My `dotnet --info` output
<details>
<summary>Click to expand details...</summary>

```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.71b9f198

Runtime Environment:
 OS Name:     endeavouros
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.71b9f198
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.125 [/usr/share/dotnet/sdk]
  8.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]

global.json file:
  /home/joe/src/Nerdbank.Streams/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
</details>

**Comment by airbreather** [comment]
As a user, I expect to see each `WriteAsync` call (well, each `FlushAsync` call) trigger exactly one message to go across to the other side.  If I'm not writing stuff too quickly, then that's exactly what happens, but it looks like if messages are getting written to the `PipeWriter` faster than they're "actually" making it into `webSocket.SendAsync`, then eventually some sort of internal optimization is combining separate messages into a single segment in the `ReadOnlySequence<byte>` instead of keeping them as separate segments.

I'm **happy** with this behavior when I want to build the message in chunks by calling [`BuffersExtensions.Write<T>`](https://learn.microsoft.com/en-us/dotnet/api/system.buffers.buffersextensions.write) with successive parts of it, but I need a reliable way to say "OK, that message is done; future writes should go to the next message we're building up".

The more I read into this, the more it starts to look like I shouldn't expect [`PipeWriter.FlushAsync`](https://learn.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipewriter.flushasync) to be responsible for signaling the higher-order concept of "end of web socket message", but I also can't find any other way to make this work for any application protocols that rely on the message boundary as a delimiter.

**Comment by airbreather** [comment]
From my perspective, based on what I know right now, I see three reasonable outcomes for this:
1. do nothing, other than maybe document that this library's `PipeWriter`-to-`WebSocket` APIs should only be used to support use cases that can handle this behavior.
    - this is the right outcome if I came to this library in the first place with unrealistic / unreasonable expectations.
2. use a new implementation of `PipeWriter` whose `FlushAsync` task only completes after `SendAsync` completes.
    - this is what I think is the best outcome overall: it should completely resolve the issue without any public API breaking changes... but it's not the cheapest, and I probably won't be able to find the time for it because I've already backed out my own usage of this library in favor of writing more directly.
3. something more complicated to use and write, where the caller has a different custom way of manually signaling "I've written the end of this message now" so that they can still `FlushAsync` for a partial message.
    - this feels **very** complicated, but it minimizes the risk of someone encountering a **behavior** breaking change, and it also has the very minor advantage of making it possible to use `endOfMessage: false` as an alternative to fully buffering every outgoing message in memory before it can be sent.

**Comment by AArnott** [comment]
Thanks for the report and thoughtful analysis. The underlying WebSocket protocol has a concept of message boundaries, but System.IO.Pipelines does _not_. So when communicating over a `WebSocket` via the Pipelines .NET API, it's impossible to write (or read) noticing message boundaries. 
In retrospect, this should be _very_ prominently documented on the Nerdbank.Streams APIs to set expectations appropriately.

In the case of writing _text_ (per your recent PR) it also means that whoever is using the `PipeWriter` must never call `FlushAsync` in between bytes that comprise a particular UTF-8 character, since we send `endOfMessage: true` with each chunk we flush, and to do so without all the bytes for a particular character would be a violation of the protocol.
