### ISSUE TITLE
Add additional TFM to reduce dependencies

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/Nerdbank.Streams#740]
### Is your feature request related to a problem? Please describe.
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

### Describe the solution you'd like
I want the package to not have a dependencies on packages which can be provided by the framework (net 6/net core 3) ie System.IO.Pipelines

### Describe alternatives you've considered
Accept the additional dependency

**Comment by AArnott** [comment]
Although https://apisof.net/catalog/f7ac641b77d48667e31915ca6b9b07ae suggests that System.IO.Pipelines is included in .NET 6, it doesn't appear to be true. And the package for it includes assemblies for net6.0, which wouldn't be the case if it was included in the runtime. So your example in particular might have been a bad one. But `System.Runtime.CompilerServices.Unsafe` is a dependency we can drop by adding a net6.0 target to the library. Would that be worthwhile to you?

**Comment by thompson-tomo** [comment]
@AArnott i just took a look at the v6 version of the package doesn't in fact include assemblies (https://www.nuget.org/packages/System.IO.Pipelines/6.0.3#dependencies-body-tab)

**Comment by AArnott** [comment]
The link shows _dependencies_. Not _content_ of the package itself. You have to download the package and look at its `lib` folder:
![image](https://github.com/dotnet/Nerdbank.Streams/assets/3548/026f3107-cbec-485a-849c-817b371a65db)
